kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: examples-role
  namespace: examples
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: examples-service-account
  namespace: examples
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: examples-role-binding
  namespace: examples
roleRef:
  kind: ClusterRole
  name: examples-role
  #apiGroup: rbac.authorization.k8s.io
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: examples-service-account
    namespace: examples
    apiGroup: ""

